name: Clean pull request

on:
  pull_request_target:
    types: [closed]

env:
  DOMAIN: echo-pr-${{ github.event.pull_request.number }}.dev.xuexb.com

jobs:
  clean-test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: clean
        uses: xuexb/dyups-actions/deploy@master
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          dyups-server: ${{ secrets.DYUPS_SERVER }}
          dyups-token: ${{ secrets.DYUPS_TOKEN }}
          domain: ${{ env.DOMAIN }}