name: Publish pull request

on:
  pull_request_target:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_VERSION: pr-${{ github.event.pull_request.number }}
  DOMAIN: echo-pr-${{ github.event.pull_request.number }}.dev.xuexb.com

jobs:
  build-and-push-image:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: source
      - name: Merge PR
        run: |
          rm -rf source/.github
          cp -r source/* .
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_ACCESS_USERNAME }}
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=${{ env.IMAGE_VERSION }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  depoly:
    needs: build-and-push-image
    if: ${{ needs.build-and-push-image.result == 'success' }}
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      version: ${{ env.IMAGE_VERSION }}
      domain: ${{ env.DOMAIN }}
  comment:
    runs-on: ubuntu-latest
    needs: depoly
    if: ${{ needs.depoly.result == 'success' }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, The deployment is successful, please visit <https://${{ env.DOMAIN }}> .✨`
            })
