name: Publish pull request

on:
  pull_request_target:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  deploy-pr:
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout PR
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: source
      - name: Merge PR
        run: |
          rm -rf source/.github/workflows
          cp -r source/* .
          rm -rf source
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.PERSONAL_ACCESS_NAME }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v2
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false
          tags: |
            type=raw,value=pr-${{ github.event.pull_request.number }}
      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: deploy
        uses: xuexb/dyups-actions/deploy@master
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-key: ${{ secrets.SSH_KEY }}
          ssh-port: ${{ secrets.SSH_PORT }}
          image: ${{ secrets.GHCR_MIRROR }}/${{ env.IMAGE_NAME }}:${{ steps.meta.outputs.version }}
          dyups-server: ${{ secrets.DYUPS_SERVER }}
          dyups-token: ${{ secrets.DYUPS_TOKEN }}
          domain: echo-${{ steps.meta.outputs.version }}.dev.xuexb.com
          container-port: 8080
      - uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, The deployment is successful, please visit <https://echo-${{ steps.meta.outputs.version }}.dev.xuexb.com> .✨`
            })
